service: orders-mngmt-v2

plugins:
  - serverless-offline
  - serverless-latest-layer-version

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  profile: test

functions:
  get-route:
    handler: dist/src/serverless.routeGet
    events:
      - httpApi: 
          method: GET 
          path: /
    layers:
      - { Ref: OrdersLambdaLayer }
  post-route:
    handler: dist/src/serverless.routePost
    events:
      - httpApi: 
          method: POST 
          path: /
    layers:
      - { Ref: OrdersLambdaLayer }
custom:
  esbuild:
    bundle: true
    minify: true
layers:
  Orders:
    path: dist/layer 
    name: orders-layer
    retain: false
    package:
      patterns:
        - "!./package.json"
        - "!./package-lock.json"
