service: ${self:custom.app.name}-layers

frameworkVersion: ${self:custom.frameworkVersion}

custom: ${file(../serverless.common.yml):custom}

provider:
  name: aws
  region: ${self:custom.region}
  profile: ${self:custom.profile}
  stage: ${self:custom.stage}

package:
  individually: true
  patterns:
    - "!**/__tests__/**"
    - "!**/__mocks__/**"
    - "!**/*.d.ts"
    - "!./package.json"
    - "!./package-lock.json"
    - '!**/tsconfig.json'
    - '!**/jest.config.js'

layers:
  common:
    path: dist/common
    name: ${self:custom.app.name}-common-${self:custom.stage}
    description: common layer for all services
    retain: false
    package:
      patterns:
        - "!./__tests__/**"
        - "!./package.json"
        - "!./package-lock.json"
